#!/usr/bin/env ruby
require 'optparse'

opts = OptionParser.new
opts.on('--noop', 'dry-run mode') { |v| $noop = true }
opts.parse!
ignore_branches = ['production', 'web01', 'web02', 'pre', 'web01-pre', 'web02-pre', 'dev', 'web01-dev', 'web02-dev']
ignore_branches.concat(['dep01', 'dep02', 'dep01-pre', 'dep01-dev'])
ignore_branches.concat(['prd', 'dlv-dev', 'dlv-pre', 'dlv-prd'])
ignore_branches.concat(['aws-prd2', 'aws-prd3', 'aws-build', 'aws-dev'])

`git branch -r`.each_line do |branch|
  branch.strip!.chomp!
  next if branch =~ %r![^/]+/master!
  next if ignore_branches.include?(branch.gsub('origin/', ''))

  if `git branch --contains #{branch}`.each_line.any? { |included| included.include?('master') }
    ref = branch.sub(%r!^([^/]+)/!, '')
    command = "git push --delete #{$1} #{ref}"
    puts command
    unless $noop
      system command
    end
  end
end
