#!/usr/bin/env ruby
require 'optparse'

opts = OptionParser.new
opts.on('--noop', 'dry-run mode') { |v| $noop = true }
opts.parse!
ignore_branches = ['add_branch_contents_cleaner']

`ls /xfs0/home/branch_contents`.each_line do |branch|
  branch.strip!.chomp!
  next if ignore_branches.include?(branch)
  command = "rm -rf /xfs0/home/branch_contents/#{branch}"
  if `git branch -r --merged`.include?(branch)
    puts command
    unless $noop
      system command
    end
  end
end
