#!/usr/bin/env ruby
require 'optparse'

opts = OptionParser.new
opts.on('--noop', 'dry-run mode') { |v| $noop = true }
opts.parse!
ignore_branches = ['master', 'production', 'web01', 'web02', 'pre', 'web01-pre', 'web02-pre', 'dev', 'web01-dev', 'web02-dev']

`git branch -r`.each_line do |branch|
  branch.strip!.chomp!
  next if ignore_branches.include?(branch.gsub('origin/', ''))

  if `git branch --contains #{branch}`.each_line.any? { |included| included.strip.chomp =~ /\A(master)\z/ }
    ref = branch.sub(%r!^([^/]+)/!, '')
    command = "git push --delete #{$1} #{ref}"
    puts command
    unless $noop
      system command
    end
  end
end
